# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.55
      name: Go build binaries and upload to release
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: LICENSE
        pre_command: "go mod tidy"
        binary_name: golang-slp-server
        release_tag: ${{ github.ref_name }}
        overwrite: true
        

    
